#!/bin/bash -f
# Vivado (TM) v2017.2 (64-bit)
#
# Filename    : hdmi_directpassthr_woi.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Apr 24 16:27:50 EDT 2018
# IP Build 1909766 on Thu Jun 15 19:58:00 MDT 2017 
#
# usage: hdmi_directpassthr_woi.sh [-help]
# usage: hdmi_directpassthr_woi.sh [-lib_map_path]
# usage: hdmi_directpassthr_woi.sh [-noclean_files]
# usage: hdmi_directpassthr_woi.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'hdmi_directpassthr_woi.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm axi_infrastructure_v1_1_0 xil_common_vip_v1_0_0 smartconnect_v1_0 axi_protocol_checker_v1_1_14 axi_vip_v1_0_2 axi_vip_v1_0_1 lib_pkg_v1_0_2 lib_cdc_v1_0_2 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_iic_v2_0_16 proc_sys_reset_v5_0_11 xlconstant_v1_1_3 xlconcat_v2_1_1 xlslice_v1_0_1 fifo_generator_v13_1_4 lib_fifo_v1_0_8 blk_mem_gen_v8_3_6 lib_bmg_v1_0_8 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_15 axi_vdma_v6_3_1 xbip_utils_v3_0_7 c_reg_fd_v12_0_3 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_3 xbip_dsp48_addsub_v3_0_3 xbip_addsub_v3_0_3 c_addsub_v12_0_10 axi_utils_v2_0_3 xbip_bram18k_v3_0_3 mult_gen_v12_0_12 floating_point_v7_0_13 xbip_dsp48_mult_v3_0_3 xbip_dsp48_multadd_v3_0_3 div_gen_v5_1_11 cordic_v6_0_11 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_13 axi_data_fifo_v2_1_12 axi_crossbar_v2_1_14 axi_protocol_converter_v2_1_13 axi_clock_converter_v2_1_12 axi_dwidth_converter_v2_1_13)

# Simulation root library directory
sim_lib_dir="vcs"

# Script info
echo -e "hdmi_directpassthr_woi.sh - Script generated by export_simulation (Vivado v2017.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "/opt/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/opt/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/opt/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_common_vip_v1_0_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl/xil_common_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v1_1_14 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/a1b2/hdl/axi_protocol_checker_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_0_2 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl/axi_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_0_1 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_processing_system7_0_0/sim/hdmi_directpassthr_woi_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/832a/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/52cb/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/0ba0/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/e956/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_iic_v2_0_16 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6bf4/hdl/axi_iic_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_iic_0_0/sim/hdmi_directpassthr_woi_axi_iic_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_11 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/5db7/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_rst_processing_system7_0_100M_0/sim/hdmi_directpassthr_woi_rst_processing_system7_0_100M_0.vhd" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/ipshared/1263/hdl/vhdl/fmc_imageon_hdmi_in.vhd" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fmc_imageon_hdmi_in_0_0/sim/hdmi_directpassthr_woi_fmc_imageon_hdmi_in_0_0.vhd" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/ipshared/c374/hdl/vhdl/adv7511_embed_syncs.vhd" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/ipshared/c374/hdl/vhdl/fmc_imageon_hdmi_out.vhd" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fmc_imageon_hdmi_out_0_0/sim/hdmi_directpassthr_woi_fmc_imageon_hdmi_out_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/45df/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_0_0/sim/hdmi_directpassthr_woi_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_1_0/sim/hdmi_directpassthr_woi_xlconstant_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/73b7/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconcat_0_3/sim/hdmi_directpassthr_woi_xlconcat_0_3.v" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/ipshared/90d2/pipeline_registers.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_0/sim/hdmi_directpassthr_woi_pipeline_registers_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlslice_v1_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/bb23/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_0_3/sim/hdmi_directpassthr_woi_xlslice_0_3.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_0_4/sim/hdmi_directpassthr_woi_xlslice_0_4.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_0_5/sim/hdmi_directpassthr_woi_xlslice_0_5.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_0_6/sim/hdmi_directpassthr_woi_xlslice_0_6.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_hblank_out_0/sim/hdmi_directpassthr_woi_hblank_out_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_de_out_0/sim/hdmi_directpassthr_woi_de_out_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_vlbank_out_0/sim/hdmi_directpassthr_woi_vlbank_out_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_1/sim/hdmi_directpassthr_woi_pipeline_registers_1_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_hdmi_sync_pass_0/sim/hdmi_directpassthr_woi_hdmi_sync_pass_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_spdif_out_0/sim/hdmi_directpassthr_woi_spdif_out_0.v" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/ipshared/ebfd/vbb_system_reset.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_vbb_system_reset_0_1/sim/hdmi_directpassthr_woi_vbb_system_reset_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_rst_processing_system7_0_150M_0/sim/hdmi_directpassthr_woi_rst_processing_system7_0_150M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_4/sim/hdmi_directpassthr_woi_pipeline_registers_1_4.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_5/sim/hdmi_directpassthr_woi_pipeline_registers_1_5.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/ebc2/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_1_4 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/ebc2/hdl/fifo_generator_v13_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/ebc2/hdl/fifo_generator_v13_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_0/sim/hdmi_directpassthr_woi_fifo_generator_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_8 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/c387/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_3_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/4158/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_8 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/0dfc/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6039/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_15 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/43a6/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_1 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_vdma_0_0/sim/hdmi_directpassthr_woi_axi_vdma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/ipshared/b79c/xup_and3.srcs/sources_1/new/xup_and3.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and3_1_0/sim/hdmi_directpassthr_woi_xup_and3_1_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_7/sim/hdmi_directpassthr_woi_pipeline_registers_1_7.v" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/ipshared/1ec9/xup_or2.srcs/sources_1/new/xup_or2.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_or2_0_1/sim/hdmi_directpassthr_woi_xup_or2_0_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_1_2/sim/hdmi_directpassthr_woi_xlconstant_1_2.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_0_4/sim/hdmi_directpassthr_woi_xlconstant_0_4.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_0_5/sim/hdmi_directpassthr_woi_xlconstant_0_5.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_0_6/sim/hdmi_directpassthr_woi_xlconstant_0_6.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_1/sim/hdmi_directpassthr_woi_fifo_generator_0_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_0_0/sim/hdmi_directpassthr_woi_xlslice_0_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconcat_0_0/sim/hdmi_directpassthr_woi_xlconcat_0_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_0_7/sim/hdmi_directpassthr_woi_xlconstant_0_7.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_0/sim/hdmi_directpassthr_woi_mean1_slice_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_concat_0/sim/hdmi_directpassthr_woi_mean1_concat_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_zero16_0/sim/hdmi_directpassthr_woi_zero16_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_1/sim/hdmi_directpassthr_woi_mean1_slice_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_concat_1/sim/hdmi_directpassthr_woi_mean1_concat_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_zero16_1/sim/hdmi_directpassthr_woi_zero16_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_2/sim/hdmi_directpassthr_woi_mean1_slice_2.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_concat_2/sim/hdmi_directpassthr_woi_mean1_concat_2.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_zero16_2/sim/hdmi_directpassthr_woi_zero16_2.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_3/sim/hdmi_directpassthr_woi_mean1_slice_3.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_concat_3/sim/hdmi_directpassthr_woi_mean1_concat_3.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_zero16_3/sim/hdmi_directpassthr_woi_zero16_3.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_4/sim/hdmi_directpassthr_woi_mean1_slice_4.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_concat_4/sim/hdmi_directpassthr_woi_mean1_concat_4.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_zero16_4/sim/hdmi_directpassthr_woi_zero16_4.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_5/sim/hdmi_directpassthr_woi_mean1_slice_5.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_concat_5/sim/hdmi_directpassthr_woi_mean1_concat_5.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_zero16_5/sim/hdmi_directpassthr_woi_zero16_5.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_6/sim/hdmi_directpassthr_woi_mean1_slice_6.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_concat_6/sim/hdmi_directpassthr_woi_mean1_concat_6.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_zero16_6/sim/hdmi_directpassthr_woi_zero16_6.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_0_8/sim/hdmi_directpassthr_woi_xlconstant_0_8.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_7 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/3d01/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_3 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/e1e2/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1e87/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_3 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7db8/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_3 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/c9c4/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_3 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2957/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_10 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/a394/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_c_addsub_0_0/sim/hdmi_directpassthr_woi_c_addsub_0_0.vhd" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_c_addsub_0_1/sim/hdmi_directpassthr_woi_c_addsub_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconcat_0_4/sim/hdmi_directpassthr_woi_xlconcat_0_4.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_0_7/sim/hdmi_directpassthr_woi_xlslice_0_7.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_7/sim/hdmi_directpassthr_woi_mean1_slice_7.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_8/sim/hdmi_directpassthr_woi_mean1_slice_8.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_9/sim/hdmi_directpassthr_woi_mean1_slice_9.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_10/sim/hdmi_directpassthr_woi_mean1_slice_10.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_11/sim/hdmi_directpassthr_woi_mean1_slice_11.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_12/sim/hdmi_directpassthr_woi_mean1_slice_12.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_13/sim/hdmi_directpassthr_woi_mean1_slice_13.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_2/sim/hdmi_directpassthr_woi_fifo_generator_0_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_vdma_0_1/sim/hdmi_directpassthr_woi_axi_vdma_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_1_3/sim/hdmi_directpassthr_woi_xlconstant_1_3.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_10_0/sim/hdmi_directpassthr_woi_pipeline_registers_10_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_or2_2_0/sim/hdmi_directpassthr_woi_xup_or2_2_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_2/sim/hdmi_directpassthr_woi_pipeline_registers_1_2.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconcat_0_5/sim/hdmi_directpassthr_woi_xlconcat_0_5.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_0_11/sim/hdmi_directpassthr_woi_xlconstant_0_11.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_0_8/sim/hdmi_directpassthr_woi_xlslice_0_8.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_3/sim/hdmi_directpassthr_woi_pipeline_registers_1_3.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconcat_0_6/sim/hdmi_directpassthr_woi_xlconcat_0_6.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_0_12/sim/hdmi_directpassthr_woi_xlconstant_0_12.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_3/sim/hdmi_directpassthr_woi_fifo_generator_0_3.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and3_0_1/sim/hdmi_directpassthr_woi_xup_and3_0_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and3_0_2/sim/hdmi_directpassthr_woi_xup_and3_0_2.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and3_1_1/sim/hdmi_directpassthr_woi_xup_and3_1_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and3_2_0/sim/hdmi_directpassthr_woi_xup_and3_2_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_4/sim/hdmi_directpassthr_woi_fifo_generator_0_4.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_1_0/sim/hdmi_directpassthr_woi_fifo_generator_1_0.v" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/ipshared/9eb7/data_packing.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_data_packing_0_0/sim/hdmi_directpassthr_woi_data_packing_0_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and3_0_3/sim/hdmi_directpassthr_woi_xup_and3_0_3.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and3_1_2/sim/hdmi_directpassthr_woi_xup_and3_1_2.v" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/ipshared/77ea/xup_and4.srcs/sources_1/new/xup_and4.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and4_0_0/sim/hdmi_directpassthr_woi_xup_and4_0_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and4_1_0/sim/hdmi_directpassthr_woi_xup_and4_1_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_5_0/sim/hdmi_directpassthr_woi_pipeline_registers_5_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_6/sim/hdmi_directpassthr_woi_pipeline_registers_1_6.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_8/sim/hdmi_directpassthr_woi_pipeline_registers_1_8.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_10/sim/hdmi_directpassthr_woi_pipeline_registers_1_10.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_11/sim/hdmi_directpassthr_woi_pipeline_registers_1_11.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_Morphology_1_0/ip/morphology_fifo/sim/morphology_fifo.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ipshared/73c7/new/morph_buf_controller.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ipshared/73c7/new/morph_err_l2.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ipshared/73c7/new/morph_err_l1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ipshared/73c7/new/morph_dia.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ipshared/73c7/new/morph_top.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_Morphology_1_0/sim/hdmi_directpassthr_woi_Morphology_1_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_0_10/sim/hdmi_directpassthr_woi_xlconstant_0_10.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_5/sim/hdmi_directpassthr_woi_fifo_generator_0_5.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_6_0/sim/hdmi_directpassthr_woi_pipeline_registers_6_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_10_1/sim/hdmi_directpassthr_woi_pipeline_registers_10_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_or2_2_1/sim/hdmi_directpassthr_woi_xup_or2_2_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_10_2/sim/hdmi_directpassthr_woi_pipeline_registers_10_2.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_or2_2_2/sim/hdmi_directpassthr_woi_xup_or2_2_2.v" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/ipshared/de12/data_unpacking.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_data_unpacking_0_0/sim/hdmi_directpassthr_woi_data_unpacking_0_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_9/sim/hdmi_directpassthr_woi_pipeline_registers_1_9.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_hblank_out_1/sim/hdmi_directpassthr_woi_hblank_out_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_de_out_1/sim/hdmi_directpassthr_woi_de_out_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_vlbank_out_1/sim/hdmi_directpassthr_woi_vlbank_out_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_12/sim/hdmi_directpassthr_woi_pipeline_registers_1_12.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_hdmi_sync_pass_1/sim/hdmi_directpassthr_woi_hdmi_sync_pass_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_spdif_out_1/sim/hdmi_directpassthr_woi_spdif_out_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_2_0/sim/hdmi_directpassthr_woi_pipeline_registers_2_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_3_0/sim/hdmi_directpassthr_woi_pipeline_registers_3_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_0_9/sim/hdmi_directpassthr_woi_xlslice_0_9.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_image_smoothing_1_0/ip/smoothing_fifo/sim/smoothing_fifo.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ipshared/6fd9/init_fifo_wr_rd_controller_smooth.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ipshared/6fd9/image_smoothing.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_image_smoothing_1_0/sim/hdmi_directpassthr_woi_image_smoothing_1_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_concatenation_0/sim/hdmi_directpassthr_woi_concatenation_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_y_sel_0/sim/hdmi_directpassthr_woi_y_sel_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_cbcr_gray_0/sim/hdmi_directpassthr_woi_cbcr_gray_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_vdma_0_2/sim/hdmi_directpassthr_woi_axi_vdma_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_6/sim/hdmi_directpassthr_woi_fifo_generator_0_6.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_7/sim/hdmi_directpassthr_woi_fifo_generator_0_7.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_8/sim/hdmi_directpassthr_woi_fifo_generator_0_8.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_data_packing_0_1/sim/hdmi_directpassthr_woi_data_packing_0_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_data_unpacking_0_1/sim/hdmi_directpassthr_woi_data_unpacking_0_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_or2_0_0/sim/hdmi_directpassthr_woi_xup_or2_0_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_0_0/sim/hdmi_directpassthr_woi_pipeline_registers_0_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_1_5/sim/hdmi_directpassthr_woi_xlconstant_1_5.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_0_1/sim/hdmi_directpassthr_woi_pipeline_registers_0_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and4_0_1/sim/hdmi_directpassthr_woi_xup_and4_0_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and4_1_1/sim/hdmi_directpassthr_woi_xup_and4_1_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and3_0_0/sim/hdmi_directpassthr_woi_xup_and3_0_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and3_1_3/sim/hdmi_directpassthr_woi_xup_and3_1_3.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and3_2_1/sim/hdmi_directpassthr_woi_xup_and3_2_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_0_2/sim/hdmi_directpassthr_woi_pipeline_registers_0_2.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_4_0/sim/hdmi_directpassthr_woi_pipeline_registers_4_0.v" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/ipshared/54ea/xup_2_to_1_mux_vector.srcs/sources_1/new/xup_2_to_1_mux_vector.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_2_to_1_mux_vector_0_0/sim/hdmi_directpassthr_woi_xup_2_to_1_mux_vector_0_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconcat_0_1/sim/hdmi_directpassthr_woi_xlconcat_0_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconcat_1_0/sim/hdmi_directpassthr_woi_xlconcat_1_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_0_1/sim/hdmi_directpassthr_woi_xlslice_0_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_1_0/sim/hdmi_directpassthr_woi_xlslice_1_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_2_0/sim/hdmi_directpassthr_woi_xlslice_2_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_3_0/sim/hdmi_directpassthr_woi_xlslice_3_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_4_0/sim/hdmi_directpassthr_woi_xlslice_4_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_5_0/sim/hdmi_directpassthr_woi_xlslice_5_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_before_smth_0/sim/hdmi_directpassthr_woi_before_smth_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_after_smth_0/sim/hdmi_directpassthr_woi_after_smth_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_smth_pass_over_0/sim/hdmi_directpassthr_woi_smth_pass_over_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_0_2/sim/hdmi_directpassthr_woi_xlslice_0_2.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_1_1/sim/hdmi_directpassthr_woi_xlslice_1_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_2_1/sim/hdmi_directpassthr_woi_xlslice_2_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_3_1/sim/hdmi_directpassthr_woi_xlslice_3_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_4_1/sim/hdmi_directpassthr_woi_xlslice_4_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_5_1/sim/hdmi_directpassthr_woi_xlslice_5_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_utils_v2_0_3 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/43f5/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_3 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/403d/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_12 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/f0ab/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_0_13 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/22e6/hdl/floating_point_v7_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_mult_v3_0_3 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/4449/hdl/xbip_dsp48_mult_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_3 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/779d/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work div_gen_v5_1_11 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/67f8/hdl/div_gen_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_MixtureOfGaussians_0_0/ip/divider_16_8/sim/divider_16_8.vhd" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_MixtureOfGaussians_0_0/ip/divider_16_9/sim/divider_16_9.vhd" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_MixtureOfGaussians_0_0/ip/mult_16x16/sim/mult_16x16.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work cordic_v6_0_11 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/5255/hdl/cordic_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_MixtureOfGaussians_0_0/ip/sqrt_core/sim/sqrt_core.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ipshared/5eb4/hdl/pipeline_registers.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ipshared/5eb4/hdl/sqrt.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ipshared/5eb4/hdl/pre_sd_up2.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ipshared/5eb4/hdl/pre_sd_up1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ipshared/5eb4/hdl/w_up.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ipshared/5eb4/hdl/wnorm.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ipshared/5eb4/hdl/vcomp.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ipshared/5eb4/hdl/sd_up.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ipshared/5eb4/hdl/mean_up.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ipshared/5eb4/hdl/match_detection.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ipshared/5eb4/hdl/fg_detection.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ipshared/5eb4/hdl/mog_top.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ipshared/5eb4/hdl/MixtureOfGaussians_v1_0_S_AXI.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ipshared/5eb4/hdl/MixtureOfGaussians_v1_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_MixtureOfGaussians_0_0/sim/hdmi_directpassthr_woi_MixtureOfGaussians_0_0.v" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/ipshared/1854/hdl/woi_det.v" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/ipshared/1854/hdl/axi_window_of_interest_detection_v1_0_S_AXI.v" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/ipshared/1854/hdl/axi_window_of_interest_detection_v1_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_window_of_interest_detection_0_0/sim/hdmi_directpassthr_woi_axi_window_of_interest_detection_0_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_window_of_interest_detection_0_1/sim/hdmi_directpassthr_woi_axi_window_of_interest_detection_0_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconcat_0_2/sim/hdmi_directpassthr_woi_xlconcat_0_2.v" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/ipshared/ed6d/video_overlay.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_video_overlay_0_2/sim/hdmi_directpassthr_woi_video_overlay_0_2.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/f9c1/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/55c0/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_12 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/95b9/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_14 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/f582/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xbar_0/sim/hdmi_directpassthr_woi_xbar_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xbar_3/sim/hdmi_directpassthr_woi_xbar_3.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xbar_1/sim/hdmi_directpassthr_woi_xbar_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xbar_2/sim/hdmi_directpassthr_woi_xbar_2.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/hdl/hdmi_directpassthr_woi.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/f0ae/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_auto_pc_3/sim/hdmi_directpassthr_woi_auto_pc_3.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_auto_pc_2/sim/hdmi_directpassthr_woi_auto_pc_2.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_12 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/80fd/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/3bde/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/1d61/hdl" +incdir+"$ref_dir/../../../../hdmi_directpassthr_woi.srcs/sources_1/bd/hdmi_directpassthr_woi/ipshared/450f/hdl" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_auto_us_1/sim/hdmi_directpassthr_woi_auto_us_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_auto_us_0/sim/hdmi_directpassthr_woi_auto_us_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_auto_ds_0/sim/hdmi_directpassthr_woi_auto_ds_0.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_auto_pc_1/sim/hdmi_directpassthr_woi_auto_pc_1.v" \
    "$ref_dir/../../../bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_auto_pc_0/sim/hdmi_directpassthr_woi_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.hdmi_directpassthr_woi xil_defaultlib.glbl -o hdmi_directpassthr_woi_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./hdmi_directpassthr_woi_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./hdmi_directpassthr_woi.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/work1/Documents/Vision_Project_WORKING_SET/vivado_vflow_working_Mar13_15_LatestRecord/vovrly_smth_mog_mrph_3rdVDMA_complete/hdmi_directpassthr_woi.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key hdmi_directpassthr_woi_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc hdmi_directpassthr_woi_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./hdmi_directpassthr_woi.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: hdmi_directpassthr_woi.sh [-help]\n\
Usage: hdmi_directpassthr_woi.sh [-lib_map_path]\n\
Usage: hdmi_directpassthr_woi.sh [-reset_run]\n\
Usage: hdmi_directpassthr_woi.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
