
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 2013.4 EDK_2013.4.20131205
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xiic.h"

/*
* The configuration table for devices
*/

XIic_Config XIic_ConfigTable[] =
{
	{
		XPAR_PROCESSOR_SUBSYSTEM_INTERCONNECT_AXI_IIC_1_DEVICE_ID,
		XPAR_PROCESSOR_SUBSYSTEM_INTERCONNECT_AXI_IIC_1_BASEADDR,
		XPAR_PROCESSOR_SUBSYSTEM_INTERCONNECT_AXI_IIC_1_TEN_BIT_ADR,
		XPAR_PROCESSOR_SUBSYSTEM_INTERCONNECT_AXI_IIC_1_GPO_WIDTH
	}
};


