webtalk_init -webtalk_dir /export/scratch/fan/vivado/vivado_vflow_working_Mar13_15/vovrly_smth_mog_mrph_3rdVDMA_complete/hdmi_directpassthr_woi.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu May 21 14:27:35 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "h6gq1i1rvtvmksq3bbg4rqdugl" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.2_32" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "32" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS release 6.6 (Final)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3000.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1432232781000" -context "sdk\\\\hardware/1432232781000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1432232781000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1432232781000"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.2" -context "sdk\\\\hardware/1432232781000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1432232781000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1432232781000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1432232781000"
webtalk_transmit -clientid 3322775763 -regid "NA" -xml /export/scratch/fan/vivado/vivado_vflow_working_Mar13_15/vovrly_smth_mog_mrph_3rdVDMA_complete/hdmi_directpassthr_woi.sdk/webtalk/usage_statistics_ext_sdk.xml -html /export/scratch/fan/vivado/vivado_vflow_working_Mar13_15/vovrly_smth_mog_mrph_3rdVDMA_complete/hdmi_directpassthr_woi.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /export/scratch/fan/vivado/vivado_vflow_working_Mar13_15/vovrly_smth_mog_mrph_3rdVDMA_complete/hdmi_directpassthr_woi.sdk/webtalk/sdk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
