
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 2013.4 EDK_2013.4.20131205
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xaxipmon.h"

/*
* The configuration table for devices
*/

XAxiPmon_Config XAxiPmon_ConfigTable[] =
{
	{
		XPAR_AXI_PERF_MON_0_DEVICE_ID,
		XPAR_AXI_PERF_MON_0_BASEADDR,
		XPAR_AXI_PERF_MON_0_GLOBAL_COUNT_WIDTH,
		XPAR_AXI_PERF_MON_0_METRICS_SAMPLE_COUNT_WIDTH,
		XPAR_AXI_PERF_MON_0_ENABLE_EVENT_COUNT,
		XPAR_AXI_PERF_MON_0_NUM_MONITOR_SLOTS,
		XPAR_AXI_PERF_MON_0_NUM_OF_COUNTERS,
		XPAR_AXI_PERF_MON_0_HAVE_SAMPLED_METRIC_CNT,
		XPAR_AXI_PERF_MON_0_ENABLE_EVENT_LOG,
		XPAR_AXI_PERF_MON_0_FIFO_AXIS_DEPTH,
		XPAR_AXI_PERF_MON_0_FIFO_AXIS_TDATA_WIDTH,
		XPAR_AXI_PERF_MON_0_FIFO_AXIS_TID_WIDTH,
		XPAR_AXI_PERF_MON_0_METRIC_COUNT_SCALE,
		XPAR_AXI_PERF_MON_0_ENABLE_ADVANCED,
		XPAR_AXI_PERF_MON_0_ENABLE_PROFILE,
		XPAR_AXI_PERF_MON_0_ENABLE_TRACE
	}
};


