
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 2013.4 EDK_2013.4.20131205
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xtmrctr.h"

/*
* The configuration table for devices
*/

XTmrCtr_Config XTmrCtr_ConfigTable[] =
{
	{
		XPAR_PROCESSOR_SUBSYSTEM_INTERCONNECT_AXI_TIMER_1_DEVICE_ID,
		XPAR_PROCESSOR_SUBSYSTEM_INTERCONNECT_AXI_TIMER_1_BASEADDR
	}
};


