# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/zedboard_fmc_imageon_hdmi_passthrough.xdc

# Block Designs: bd/hdmi_directpassthr_woi/hdmi_directpassthr_woi.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi || ORIG_REF_NAME==hdmi_directpassthr_woi}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_processing_system7_0_0/hdmi_directpassthr_woi_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_processing_system7_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_processing_system7_0_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_iic_0_0/hdmi_directpassthr_woi_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_axi_iic_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_axi_iic_0_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_processing_system7_0_axi_periph_0/hdmi_directpassthr_woi_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_processing_system7_0_axi_periph_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_rst_processing_system7_0_100M_0/hdmi_directpassthr_woi_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_rst_processing_system7_0_100M_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fmc_imageon_hdmi_in_0_0/hdmi_directpassthr_woi_fmc_imageon_hdmi_in_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fmc_imageon_hdmi_in_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_fmc_imageon_hdmi_in_0_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fmc_imageon_hdmi_out_0_0/hdmi_directpassthr_woi_fmc_imageon_hdmi_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fmc_imageon_hdmi_out_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_fmc_imageon_hdmi_out_0_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_0_0/hdmi_directpassthr_woi_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlconstant_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlconstant_0_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_1_0/hdmi_directpassthr_woi_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlconstant_1_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlconstant_1_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconcat_0_3/hdmi_directpassthr_woi_xlconcat_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlconcat_0_3 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlconcat_0_3}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_0/hdmi_directpassthr_woi_pipeline_registers_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_0_3/hdmi_directpassthr_woi_xlslice_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlslice_0_3 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlslice_0_3}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_0_4/hdmi_directpassthr_woi_xlslice_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlslice_0_4 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlslice_0_4}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_0_5/hdmi_directpassthr_woi_xlslice_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlslice_0_5 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlslice_0_5}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_0_6/hdmi_directpassthr_woi_xlslice_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlslice_0_6 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlslice_0_6}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_hblank_out_0/hdmi_directpassthr_woi_hblank_out_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_hblank_out_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_hblank_out_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_de_out_0/hdmi_directpassthr_woi_de_out_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_de_out_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_de_out_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_vlbank_out_0/hdmi_directpassthr_woi_vlbank_out_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_vlbank_out_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_vlbank_out_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_1/hdmi_directpassthr_woi_pipeline_registers_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_hdmi_sync_pass_0/hdmi_directpassthr_woi_hdmi_sync_pass_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_hdmi_sync_pass_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_hdmi_sync_pass_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_spdif_out_0/hdmi_directpassthr_woi_spdif_out_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_spdif_out_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_spdif_out_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_vbb_system_reset_0_1/hdmi_directpassthr_woi_vbb_system_reset_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_vbb_system_reset_0_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_vbb_system_reset_0_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_mem_intercon_0/hdmi_directpassthr_woi_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_axi_mem_intercon_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_axi_mem_intercon_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_rst_processing_system7_0_150M_0/hdmi_directpassthr_woi_rst_processing_system7_0_150M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_rst_processing_system7_0_150M_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_rst_processing_system7_0_150M_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_4/hdmi_directpassthr_woi_pipeline_registers_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_4 || ORIG_REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_4}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_5/hdmi_directpassthr_woi_pipeline_registers_1_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_5 || ORIG_REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_5}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_0/hdmi_directpassthr_woi_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_vdma_0_0/hdmi_directpassthr_woi_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_axi_vdma_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_axi_vdma_0_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and3_1_0/hdmi_directpassthr_woi_xup_and3_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xup_and3_1_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_xup_and3_1_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_7/hdmi_directpassthr_woi_pipeline_registers_1_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_7 || ORIG_REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_7}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_or2_0_1/hdmi_directpassthr_woi_xup_or2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xup_or2_0_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_xup_or2_0_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_1_2/hdmi_directpassthr_woi_xlconstant_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlconstant_1_2 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlconstant_1_2}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_0_4/hdmi_directpassthr_woi_xlconstant_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlconstant_0_4 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlconstant_0_4}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_0_5/hdmi_directpassthr_woi_xlconstant_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlconstant_0_5 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlconstant_0_5}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_0_6/hdmi_directpassthr_woi_xlconstant_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlconstant_0_6 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlconstant_0_6}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_1/hdmi_directpassthr_woi_fifo_generator_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_0_0/hdmi_directpassthr_woi_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlslice_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlslice_0_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconcat_0_0/hdmi_directpassthr_woi_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlconcat_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlconcat_0_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_0_7/hdmi_directpassthr_woi_xlconstant_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlconstant_0_7 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlconstant_0_7}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_0/hdmi_directpassthr_woi_mean1_slice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_mean1_slice_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_mean1_slice_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_concat_0/hdmi_directpassthr_woi_mean1_concat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_mean1_concat_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_mean1_concat_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_zero16_0/hdmi_directpassthr_woi_zero16_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_zero16_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_zero16_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_1/hdmi_directpassthr_woi_mean1_slice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_mean1_slice_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_mean1_slice_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_concat_1/hdmi_directpassthr_woi_mean1_concat_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_mean1_concat_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_mean1_concat_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_zero16_1/hdmi_directpassthr_woi_zero16_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_zero16_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_zero16_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_2/hdmi_directpassthr_woi_mean1_slice_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_mean1_slice_2 || ORIG_REF_NAME==hdmi_directpassthr_woi_mean1_slice_2}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_concat_2/hdmi_directpassthr_woi_mean1_concat_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_mean1_concat_2 || ORIG_REF_NAME==hdmi_directpassthr_woi_mean1_concat_2}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_zero16_2/hdmi_directpassthr_woi_zero16_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_zero16_2 || ORIG_REF_NAME==hdmi_directpassthr_woi_zero16_2}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_3/hdmi_directpassthr_woi_mean1_slice_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_mean1_slice_3 || ORIG_REF_NAME==hdmi_directpassthr_woi_mean1_slice_3}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_concat_3/hdmi_directpassthr_woi_mean1_concat_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_mean1_concat_3 || ORIG_REF_NAME==hdmi_directpassthr_woi_mean1_concat_3}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_zero16_3/hdmi_directpassthr_woi_zero16_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_zero16_3 || ORIG_REF_NAME==hdmi_directpassthr_woi_zero16_3}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_4/hdmi_directpassthr_woi_mean1_slice_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_mean1_slice_4 || ORIG_REF_NAME==hdmi_directpassthr_woi_mean1_slice_4}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_concat_4/hdmi_directpassthr_woi_mean1_concat_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_mean1_concat_4 || ORIG_REF_NAME==hdmi_directpassthr_woi_mean1_concat_4}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_zero16_4/hdmi_directpassthr_woi_zero16_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_zero16_4 || ORIG_REF_NAME==hdmi_directpassthr_woi_zero16_4}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_5/hdmi_directpassthr_woi_mean1_slice_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_mean1_slice_5 || ORIG_REF_NAME==hdmi_directpassthr_woi_mean1_slice_5}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_concat_5/hdmi_directpassthr_woi_mean1_concat_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_mean1_concat_5 || ORIG_REF_NAME==hdmi_directpassthr_woi_mean1_concat_5}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_zero16_5/hdmi_directpassthr_woi_zero16_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_zero16_5 || ORIG_REF_NAME==hdmi_directpassthr_woi_zero16_5}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_6/hdmi_directpassthr_woi_mean1_slice_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_mean1_slice_6 || ORIG_REF_NAME==hdmi_directpassthr_woi_mean1_slice_6}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_concat_6/hdmi_directpassthr_woi_mean1_concat_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_mean1_concat_6 || ORIG_REF_NAME==hdmi_directpassthr_woi_mean1_concat_6}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_zero16_6/hdmi_directpassthr_woi_zero16_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_zero16_6 || ORIG_REF_NAME==hdmi_directpassthr_woi_zero16_6}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_0_8/hdmi_directpassthr_woi_xlconstant_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlconstant_0_8 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlconstant_0_8}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_c_addsub_0_0/hdmi_directpassthr_woi_c_addsub_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_c_addsub_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_c_addsub_0_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_c_addsub_0_1/hdmi_directpassthr_woi_c_addsub_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_c_addsub_0_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_c_addsub_0_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconcat_0_4/hdmi_directpassthr_woi_xlconcat_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlconcat_0_4 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlconcat_0_4}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_0_7/hdmi_directpassthr_woi_xlslice_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlslice_0_7 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlslice_0_7}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_7/hdmi_directpassthr_woi_mean1_slice_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_mean1_slice_7 || ORIG_REF_NAME==hdmi_directpassthr_woi_mean1_slice_7}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_8/hdmi_directpassthr_woi_mean1_slice_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_mean1_slice_8 || ORIG_REF_NAME==hdmi_directpassthr_woi_mean1_slice_8}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_9/hdmi_directpassthr_woi_mean1_slice_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_mean1_slice_9 || ORIG_REF_NAME==hdmi_directpassthr_woi_mean1_slice_9}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_10/hdmi_directpassthr_woi_mean1_slice_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_mean1_slice_10 || ORIG_REF_NAME==hdmi_directpassthr_woi_mean1_slice_10}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_11/hdmi_directpassthr_woi_mean1_slice_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_mean1_slice_11 || ORIG_REF_NAME==hdmi_directpassthr_woi_mean1_slice_11}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_12/hdmi_directpassthr_woi_mean1_slice_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_mean1_slice_12 || ORIG_REF_NAME==hdmi_directpassthr_woi_mean1_slice_12}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_mean1_slice_13/hdmi_directpassthr_woi_mean1_slice_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_mean1_slice_13 || ORIG_REF_NAME==hdmi_directpassthr_woi_mean1_slice_13}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_2/hdmi_directpassthr_woi_fifo_generator_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_2 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_2}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_vdma_0_1/hdmi_directpassthr_woi_axi_vdma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_axi_vdma_0_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_axi_vdma_0_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_mem_intercon_1_0/hdmi_directpassthr_woi_axi_mem_intercon_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_axi_mem_intercon_1_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_axi_mem_intercon_1_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_1_3/hdmi_directpassthr_woi_xlconstant_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlconstant_1_3 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlconstant_1_3}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_10_0/hdmi_directpassthr_woi_pipeline_registers_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_pipeline_registers_10_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_pipeline_registers_10_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_or2_2_0/hdmi_directpassthr_woi_xup_or2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xup_or2_2_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_xup_or2_2_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_2/hdmi_directpassthr_woi_pipeline_registers_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_2 || ORIG_REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_2}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconcat_0_5/hdmi_directpassthr_woi_xlconcat_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlconcat_0_5 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlconcat_0_5}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_0_11/hdmi_directpassthr_woi_xlconstant_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlconstant_0_11 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlconstant_0_11}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_0_8/hdmi_directpassthr_woi_xlslice_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlslice_0_8 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlslice_0_8}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_3/hdmi_directpassthr_woi_pipeline_registers_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_3 || ORIG_REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_3}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconcat_0_6/hdmi_directpassthr_woi_xlconcat_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlconcat_0_6 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlconcat_0_6}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_0_12/hdmi_directpassthr_woi_xlconstant_0_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlconstant_0_12 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlconstant_0_12}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_3/hdmi_directpassthr_woi_fifo_generator_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_3 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_3}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and3_0_1/hdmi_directpassthr_woi_xup_and3_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xup_and3_0_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_xup_and3_0_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and3_0_2/hdmi_directpassthr_woi_xup_and3_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xup_and3_0_2 || ORIG_REF_NAME==hdmi_directpassthr_woi_xup_and3_0_2}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and3_1_1/hdmi_directpassthr_woi_xup_and3_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xup_and3_1_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_xup_and3_1_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and3_2_0/hdmi_directpassthr_woi_xup_and3_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xup_and3_2_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_xup_and3_2_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_4/hdmi_directpassthr_woi_fifo_generator_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_4 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_4}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_1_0/hdmi_directpassthr_woi_fifo_generator_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_1_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_1_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_data_packing_0_0/hdmi_directpassthr_woi_data_packing_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_data_packing_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_data_packing_0_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and3_0_3/hdmi_directpassthr_woi_xup_and3_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xup_and3_0_3 || ORIG_REF_NAME==hdmi_directpassthr_woi_xup_and3_0_3}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and3_1_2/hdmi_directpassthr_woi_xup_and3_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xup_and3_1_2 || ORIG_REF_NAME==hdmi_directpassthr_woi_xup_and3_1_2}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and4_0_0/hdmi_directpassthr_woi_xup_and4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xup_and4_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_xup_and4_0_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and4_1_0/hdmi_directpassthr_woi_xup_and4_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xup_and4_1_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_xup_and4_1_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_5_0/hdmi_directpassthr_woi_pipeline_registers_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_pipeline_registers_5_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_pipeline_registers_5_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_6/hdmi_directpassthr_woi_pipeline_registers_1_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_6 || ORIG_REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_6}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_8/hdmi_directpassthr_woi_pipeline_registers_1_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_8 || ORIG_REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_8}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_10/hdmi_directpassthr_woi_pipeline_registers_1_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_10 || ORIG_REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_10}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_11/hdmi_directpassthr_woi_pipeline_registers_1_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_11 || ORIG_REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_11}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_Morphology_1_0/hdmi_directpassthr_woi_Morphology_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_Morphology_1_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_Morphology_1_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_Morphology_1_0/ip/morphology_fifo/morphology_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==morphology_fifo || ORIG_REF_NAME==morphology_fifo}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_0_10/hdmi_directpassthr_woi_xlconstant_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlconstant_0_10 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlconstant_0_10}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_5/hdmi_directpassthr_woi_fifo_generator_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_5 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_5}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_6_0/hdmi_directpassthr_woi_pipeline_registers_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_pipeline_registers_6_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_pipeline_registers_6_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_10_1/hdmi_directpassthr_woi_pipeline_registers_10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_pipeline_registers_10_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_pipeline_registers_10_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_or2_2_1/hdmi_directpassthr_woi_xup_or2_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xup_or2_2_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_xup_or2_2_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_10_2/hdmi_directpassthr_woi_pipeline_registers_10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_pipeline_registers_10_2 || ORIG_REF_NAME==hdmi_directpassthr_woi_pipeline_registers_10_2}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_or2_2_2/hdmi_directpassthr_woi_xup_or2_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xup_or2_2_2 || ORIG_REF_NAME==hdmi_directpassthr_woi_xup_or2_2_2}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_data_unpacking_0_0/hdmi_directpassthr_woi_data_unpacking_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_data_unpacking_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_data_unpacking_0_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_9/hdmi_directpassthr_woi_pipeline_registers_1_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_9 || ORIG_REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_9}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_hblank_out_1/hdmi_directpassthr_woi_hblank_out_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_hblank_out_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_hblank_out_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_de_out_1/hdmi_directpassthr_woi_de_out_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_de_out_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_de_out_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_vlbank_out_1/hdmi_directpassthr_woi_vlbank_out_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_vlbank_out_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_vlbank_out_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_1_12/hdmi_directpassthr_woi_pipeline_registers_1_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_12 || ORIG_REF_NAME==hdmi_directpassthr_woi_pipeline_registers_1_12}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_hdmi_sync_pass_1/hdmi_directpassthr_woi_hdmi_sync_pass_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_hdmi_sync_pass_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_hdmi_sync_pass_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_spdif_out_1/hdmi_directpassthr_woi_spdif_out_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_spdif_out_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_spdif_out_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_2_0/hdmi_directpassthr_woi_pipeline_registers_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_pipeline_registers_2_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_pipeline_registers_2_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_3_0/hdmi_directpassthr_woi_pipeline_registers_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_pipeline_registers_3_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_pipeline_registers_3_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_0_9/hdmi_directpassthr_woi_xlslice_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlslice_0_9 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlslice_0_9}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_image_smoothing_1_0/hdmi_directpassthr_woi_image_smoothing_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_image_smoothing_1_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_image_smoothing_1_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_image_smoothing_1_0/ip/smoothing_fifo/smoothing_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==smoothing_fifo || ORIG_REF_NAME==smoothing_fifo}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_concatenation_0/hdmi_directpassthr_woi_concatenation_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_concatenation_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_concatenation_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_y_sel_0/hdmi_directpassthr_woi_y_sel_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_y_sel_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_y_sel_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_cbcr_gray_0/hdmi_directpassthr_woi_cbcr_gray_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_cbcr_gray_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_cbcr_gray_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_vdma_0_2/hdmi_directpassthr_woi_axi_vdma_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_axi_vdma_0_2 || ORIG_REF_NAME==hdmi_directpassthr_woi_axi_vdma_0_2}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_6/hdmi_directpassthr_woi_fifo_generator_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_6 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_6}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_7/hdmi_directpassthr_woi_fifo_generator_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_7 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_7}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_8/hdmi_directpassthr_woi_fifo_generator_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_8 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_8}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_data_packing_0_1/hdmi_directpassthr_woi_data_packing_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_data_packing_0_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_data_packing_0_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_data_unpacking_0_1/hdmi_directpassthr_woi_data_unpacking_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_data_unpacking_0_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_data_unpacking_0_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_mem_intercon_2_0/hdmi_directpassthr_woi_axi_mem_intercon_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_axi_mem_intercon_2_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_axi_mem_intercon_2_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_or2_0_0/hdmi_directpassthr_woi_xup_or2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xup_or2_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_xup_or2_0_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_0_0/hdmi_directpassthr_woi_pipeline_registers_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_pipeline_registers_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_pipeline_registers_0_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconstant_1_5/hdmi_directpassthr_woi_xlconstant_1_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlconstant_1_5 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlconstant_1_5}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_0_1/hdmi_directpassthr_woi_pipeline_registers_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_pipeline_registers_0_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_pipeline_registers_0_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and4_0_1/hdmi_directpassthr_woi_xup_and4_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xup_and4_0_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_xup_and4_0_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and4_1_1/hdmi_directpassthr_woi_xup_and4_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xup_and4_1_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_xup_and4_1_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and3_0_0/hdmi_directpassthr_woi_xup_and3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xup_and3_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_xup_and3_0_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and3_1_3/hdmi_directpassthr_woi_xup_and3_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xup_and3_1_3 || ORIG_REF_NAME==hdmi_directpassthr_woi_xup_and3_1_3}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_and3_2_1/hdmi_directpassthr_woi_xup_and3_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xup_and3_2_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_xup_and3_2_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_0_2/hdmi_directpassthr_woi_pipeline_registers_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_pipeline_registers_0_2 || ORIG_REF_NAME==hdmi_directpassthr_woi_pipeline_registers_0_2}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_pipeline_registers_4_0/hdmi_directpassthr_woi_pipeline_registers_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_pipeline_registers_4_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_pipeline_registers_4_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xup_2_to_1_mux_vector_0_0/hdmi_directpassthr_woi_xup_2_to_1_mux_vector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xup_2_to_1_mux_vector_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_xup_2_to_1_mux_vector_0_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconcat_0_1/hdmi_directpassthr_woi_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlconcat_0_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlconcat_0_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconcat_1_0/hdmi_directpassthr_woi_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlconcat_1_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlconcat_1_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_0_1/hdmi_directpassthr_woi_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlslice_0_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlslice_0_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_1_0/hdmi_directpassthr_woi_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlslice_1_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlslice_1_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_2_0/hdmi_directpassthr_woi_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlslice_2_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlslice_2_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_3_0/hdmi_directpassthr_woi_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlslice_3_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlslice_3_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_4_0/hdmi_directpassthr_woi_xlslice_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlslice_4_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlslice_4_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_5_0/hdmi_directpassthr_woi_xlslice_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlslice_5_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlslice_5_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_before_smth_0/hdmi_directpassthr_woi_before_smth_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_before_smth_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_before_smth_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_after_smth_0/hdmi_directpassthr_woi_after_smth_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_after_smth_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_after_smth_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_smth_pass_over_0/hdmi_directpassthr_woi_smth_pass_over_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_smth_pass_over_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_smth_pass_over_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_0_2/hdmi_directpassthr_woi_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlslice_0_2 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlslice_0_2}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_1_1/hdmi_directpassthr_woi_xlslice_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlslice_1_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlslice_1_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_2_1/hdmi_directpassthr_woi_xlslice_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlslice_2_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlslice_2_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_3_1/hdmi_directpassthr_woi_xlslice_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlslice_3_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlslice_3_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_4_1/hdmi_directpassthr_woi_xlslice_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlslice_4_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlslice_4_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlslice_5_1/hdmi_directpassthr_woi_xlslice_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlslice_5_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlslice_5_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_MixtureOfGaussians_0_0/hdmi_directpassthr_woi_MixtureOfGaussians_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_MixtureOfGaussians_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_MixtureOfGaussians_0_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_MixtureOfGaussians_0_0/ip/divider_16_8/divider_16_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider_16_8 || ORIG_REF_NAME==divider_16_8}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_MixtureOfGaussians_0_0/ip/divider_16_9/divider_16_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider_16_9 || ORIG_REF_NAME==divider_16_9}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_MixtureOfGaussians_0_0/ip/mult_16x16/mult_16x16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_16x16 || ORIG_REF_NAME==mult_16x16}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_MixtureOfGaussians_0_0/ip/sqrt_core/sqrt_core.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sqrt_core || ORIG_REF_NAME==sqrt_core}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_window_of_interest_detection_0_0/hdmi_directpassthr_woi_axi_window_of_interest_detection_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_axi_window_of_interest_detection_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_axi_window_of_interest_detection_0_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_window_of_interest_detection_0_1/hdmi_directpassthr_woi_axi_window_of_interest_detection_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_axi_window_of_interest_detection_0_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_axi_window_of_interest_detection_0_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xlconcat_0_2/hdmi_directpassthr_woi_xlconcat_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xlconcat_0_2 || ORIG_REF_NAME==hdmi_directpassthr_woi_xlconcat_0_2}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_video_overlay_0_2/hdmi_directpassthr_woi_video_overlay_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_video_overlay_0_2 || ORIG_REF_NAME==hdmi_directpassthr_woi_video_overlay_0_2}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xbar_0/hdmi_directpassthr_woi_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xbar_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_xbar_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xbar_3/hdmi_directpassthr_woi_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xbar_3 || ORIG_REF_NAME==hdmi_directpassthr_woi_xbar_3}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xbar_1/hdmi_directpassthr_woi_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xbar_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_xbar_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xbar_2/hdmi_directpassthr_woi_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_xbar_2 || ORIG_REF_NAME==hdmi_directpassthr_woi_xbar_2}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_auto_pc_3/hdmi_directpassthr_woi_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_auto_pc_3 || ORIG_REF_NAME==hdmi_directpassthr_woi_auto_pc_3}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_auto_pc_2/hdmi_directpassthr_woi_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_auto_pc_2 || ORIG_REF_NAME==hdmi_directpassthr_woi_auto_pc_2}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_auto_us_1/hdmi_directpassthr_woi_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_auto_us_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_auto_us_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_auto_us_0/hdmi_directpassthr_woi_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_auto_us_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_auto_us_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_auto_ds_0/hdmi_directpassthr_woi_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_auto_ds_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_auto_ds_0}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_auto_pc_1/hdmi_directpassthr_woi_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_auto_pc_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_auto_pc_1}]

# IP: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_auto_pc_0/hdmi_directpassthr_woi_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_auto_pc_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_auto_pc_0}]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_processing_system7_0_0/hdmi_directpassthr_woi_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_processing_system7_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_iic_0_0/hdmi_directpassthr_woi_axi_iic_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_axi_iic_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_axi_iic_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_iic_0_0/hdmi_directpassthr_woi_axi_iic_0_0_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_rst_processing_system7_0_100M_0/hdmi_directpassthr_woi_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_rst_processing_system7_0_100M_0/hdmi_directpassthr_woi_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_rst_processing_system7_0_100M_0/hdmi_directpassthr_woi_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_rst_processing_system7_0_150M_0/hdmi_directpassthr_woi_rst_processing_system7_0_150M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_rst_processing_system7_0_150M_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_rst_processing_system7_0_150M_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_rst_processing_system7_0_150M_0/hdmi_directpassthr_woi_rst_processing_system7_0_150M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_rst_processing_system7_0_150M_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_rst_processing_system7_0_150M_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_rst_processing_system7_0_150M_0/hdmi_directpassthr_woi_rst_processing_system7_0_150M_0_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_0/hdmi_directpassthr_woi_fifo_generator_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_0/hdmi_directpassthr_woi_fifo_generator_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_0/hdmi_directpassthr_woi_fifo_generator_0_0_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_vdma_0_0/hdmi_directpassthr_woi_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_axi_vdma_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_vdma_0_0/hdmi_directpassthr_woi_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_axi_vdma_0_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_vdma_0_0/hdmi_directpassthr_woi_axi_vdma_0_0_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_1/hdmi_directpassthr_woi_fifo_generator_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_1}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_1/hdmi_directpassthr_woi_fifo_generator_0_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_1}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_1/hdmi_directpassthr_woi_fifo_generator_0_1_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_2/hdmi_directpassthr_woi_fifo_generator_0_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_2 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_2}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_2/hdmi_directpassthr_woi_fifo_generator_0_2_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_2 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_2}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_2/hdmi_directpassthr_woi_fifo_generator_0_2_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_vdma_0_1/hdmi_directpassthr_woi_axi_vdma_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_axi_vdma_0_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_axi_vdma_0_1}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_vdma_0_1/hdmi_directpassthr_woi_axi_vdma_0_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_axi_vdma_0_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_axi_vdma_0_1}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_vdma_0_1/hdmi_directpassthr_woi_axi_vdma_0_1_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_3/hdmi_directpassthr_woi_fifo_generator_0_3.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_3 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_3}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_3/hdmi_directpassthr_woi_fifo_generator_0_3_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_4/hdmi_directpassthr_woi_fifo_generator_0_4.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_4 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_4}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_4/hdmi_directpassthr_woi_fifo_generator_0_4_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_1_0/hdmi_directpassthr_woi_fifo_generator_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_1_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_1_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_1_0/hdmi_directpassthr_woi_fifo_generator_1_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_1_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_1_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_1_0/hdmi_directpassthr_woi_fifo_generator_1_0_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_Morphology_1_0/ip/morphology_fifo/morphology_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==morphology_fifo || ORIG_REF_NAME==morphology_fifo}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_5/hdmi_directpassthr_woi_fifo_generator_0_5.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_5 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_5}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_5/hdmi_directpassthr_woi_fifo_generator_0_5_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_image_smoothing_1_0/ip/smoothing_fifo/smoothing_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==smoothing_fifo || ORIG_REF_NAME==smoothing_fifo}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_vdma_0_2/hdmi_directpassthr_woi_axi_vdma_0_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_axi_vdma_0_2 || ORIG_REF_NAME==hdmi_directpassthr_woi_axi_vdma_0_2}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_vdma_0_2/hdmi_directpassthr_woi_axi_vdma_0_2_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_axi_vdma_0_2 || ORIG_REF_NAME==hdmi_directpassthr_woi_axi_vdma_0_2}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_axi_vdma_0_2/hdmi_directpassthr_woi_axi_vdma_0_2_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_6/hdmi_directpassthr_woi_fifo_generator_0_6.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_6 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_6}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_6/hdmi_directpassthr_woi_fifo_generator_0_6_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_6 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_6}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_6/hdmi_directpassthr_woi_fifo_generator_0_6_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_7/hdmi_directpassthr_woi_fifo_generator_0_7.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_7 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_7}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_7/hdmi_directpassthr_woi_fifo_generator_0_7_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_8/hdmi_directpassthr_woi_fifo_generator_0_8.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_8 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_8}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_8/hdmi_directpassthr_woi_fifo_generator_0_8_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_8 || ORIG_REF_NAME==hdmi_directpassthr_woi_fifo_generator_0_8}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_fifo_generator_0_8/hdmi_directpassthr_woi_fifo_generator_0_8_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xbar_0/hdmi_directpassthr_woi_xbar_0_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xbar_3/hdmi_directpassthr_woi_xbar_3_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xbar_1/hdmi_directpassthr_woi_xbar_1_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_xbar_2/hdmi_directpassthr_woi_xbar_2_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_auto_pc_3/hdmi_directpassthr_woi_auto_pc_3_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_auto_pc_2/hdmi_directpassthr_woi_auto_pc_2_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_auto_us_1/hdmi_directpassthr_woi_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_auto_us_1 || ORIG_REF_NAME==hdmi_directpassthr_woi_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_auto_us_1/hdmi_directpassthr_woi_auto_us_1_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_auto_us_0/hdmi_directpassthr_woi_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_auto_us_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_auto_us_0/hdmi_directpassthr_woi_auto_us_0_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_auto_ds_0/hdmi_directpassthr_woi_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_directpassthr_woi_auto_ds_0 || ORIG_REF_NAME==hdmi_directpassthr_woi_auto_ds_0}] {/inst }]/inst ]]

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_auto_ds_0/hdmi_directpassthr_woi_auto_ds_0_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_auto_pc_1/hdmi_directpassthr_woi_auto_pc_1_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/ip/hdmi_directpassthr_woi_auto_pc_0/hdmi_directpassthr_woi_auto_pc_0_ooc.xdc

# XDC: bd/hdmi_directpassthr_woi/hdmi_directpassthr_woi_ooc.xdc
