
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 2013.4 EDK_2013.4.20131205
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xvtc.h"

/*
* The configuration table for devices
*/

XVtc_Config XVtc_ConfigTable[] =
{
	{
		XPAR_VIDEO_PIPELINE_VIDEO_OUT_V_TC_1_DEVICE_ID,
		XPAR_VIDEO_PIPELINE_VIDEO_OUT_V_TC_1_BASEADDR
	}
};


