
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 2013.4 EDK_2013.4.20131205
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xuartlite.h"

/*
* The configuration table for devices
*/

XUartLite_Config XUartLite_ConfigTable[] =
{
	{
		XPAR_PROCESSOR_SUBSYSTEM_AXI_UARTLITE_1_DEVICE_ID,
		XPAR_PROCESSOR_SUBSYSTEM_AXI_UARTLITE_1_BASEADDR,
		XPAR_PROCESSOR_SUBSYSTEM_AXI_UARTLITE_1_BAUDRATE,
		XPAR_PROCESSOR_SUBSYSTEM_AXI_UARTLITE_1_USE_PARITY,
		XPAR_PROCESSOR_SUBSYSTEM_AXI_UARTLITE_1_ODD_PARITY,
		XPAR_PROCESSOR_SUBSYSTEM_AXI_UARTLITE_1_DATA_BITS
	},
	{
		XPAR_PROCESSOR_SUBSYSTEM_MDM_1_DEVICE_ID,
		XPAR_PROCESSOR_SUBSYSTEM_MDM_1_BASEADDR,
		XPAR_PROCESSOR_SUBSYSTEM_MDM_1_BAUDRATE,
		XPAR_PROCESSOR_SUBSYSTEM_MDM_1_USE_PARITY,
		XPAR_PROCESSOR_SUBSYSTEM_MDM_1_ODD_PARITY,
		XPAR_PROCESSOR_SUBSYSTEM_MDM_1_DATA_BITS
	}
};


