
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 2013.4 EDK_2013.4.20131205
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xintc.h"


extern void XNullHandler (void *);

/*
* The configuration table for devices
*/

XIntc_Config XIntc_ConfigTable[] =
{
	{
		XPAR_PROCESSOR_SUBSYSTEM_INTERCONNECT_AXI_INTC_1_DEVICE_ID,
		XPAR_PROCESSOR_SUBSYSTEM_INTERCONNECT_AXI_INTC_1_BASEADDR,
		XPAR_PROCESSOR_SUBSYSTEM_INTERCONNECT_AXI_INTC_1_KIND_OF_INTR,
		XPAR_PROCESSOR_SUBSYSTEM_INTERCONNECT_AXI_INTC_1_HAS_FAST,
		XPAR_PROCESSOR_SUBSYSTEM_INTERCONNECT_AXI_INTC_1_IVAR_RESET_VALUE,
		XPAR_PROCESSOR_SUBSYSTEM_INTERCONNECT_AXI_INTC_1_NUM_INTR_INPUTS,
		XIN_SVC_SGL_ISR_OPTION,
		XPAR_PROCESSOR_SUBSYSTEM_INTERCONNECT_AXI_INTC_1_TYPE,
		{
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			}
		}

	}
};

